### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by adriamt** [andycandy-de/SimpleAndroidBridge#3]
Hi,

I've seen that you use `setTimeout` function with the default value of timeout. It's possible to make this value dynamic or at least to change it?

Thanks

**Comment by andycandy-de** [comment]
Do you mean the `setTimeout` call in `bridge.nativeCallFullPromise` and `bridge.nativeCallWebPromise` (https://github.com/andycandy-de/SimpleAndroidBridge/blob/development/SimpleAndoirdBridgeLibJS/src/main/js/init.js)? What's the problem with the default value? I don't understand why do you want to change it? Could you explain?

How does the lib works for you? Would be great to get some feedback

**Comment by adriamt** [comment]
Yeah sorry.

I'm using your library on an app that has a webview to show some website. When certain button of the website is pressed, we receive this event on the app and we launch an http request to an API endpoint. This call opens another app on the Android terminal and when the action is done the api call returns an error or not. After we receive the response we call back to the website using your promises, tell to the website if there was an error.

If we use this scenario with to devices (the second app is opened to another device) it works like charm. The problem occurs when the second app is opened on the same device. After we receive the http call response, we call the promise, but the website most of the times does not find out of the event.

We cannot debug due to some limitations of the devices we are using so it's hard what is happening and I thought that maybe your timeout was removing the promise before it gets called.

But maybe is another thing... :S

**Comment by andycandy-de** [comment]
I don't think that the `setTimeout` is the problem. I just added it to queue the native call for the next execution of the javascript event loop. So the actual javascript stack can ends. The native method is executed when the function in `setTimeout` is called.
I think following situations could be the reason for your case:
 - The bridge is reinitiated for some reason (unlikely  - Could be the case if you reinitiated the website or the webview)
 - The app is terminated by the OS (unlikely)
 - The app is in the background (likely - See explanation below)

I think the problem is that you call another app, which gets the focus. I assume that your app is unfocused and android / javascript loopers are paused. So you will not get the native promise call until the app is focused again. That is a plausible explanation of the problem. That would also explain why the two devices use cases works.

**Comment by adriamt** [comment]
Well, I'm still figuring what could be the problem because

**Comment by adriamt** [comment]
when

**Comment by adriamt** [comment]
Well I'm still figuring out what could be the problem because when the second app returns an error the Promise works fine.

I don't think that any of the 3 reasons that you mention could be the problem, but for the moment I'm still clueless and not being able to debug doesn't help.

Thanks anyway ;)

**Comment by andycandy-de** [comment]
But if an error happens in the second app, the second app is closed and your app is focused again? What if no error happens in the second app? Is your app in the foreground or in the background?
But if the error case works, the `setTimeout` cannot be the reason for the not working positive case.
I hope you find the problem.
